arduino example
planet-nine-app/sessionless pull request #60
Opened 2024-06-19 05:33 UTC by zach-planet-nine

This PR adds a simple Arduino example. It requires a TwoWay Peripheral which you can find in the MAGIC repo.

2024-06-19 10:04 UTC, FssAy requested changes

2024-06-19 10:04 UTC, FssAy commented on src/cpp/client/example/arduino/LEDTEST/Archive.zip
It appears to be the entire example packed in an archive. I am not familiar with Arduino, but I believe that was committed by mistake.

2024-06-19 23:49 UTC, zach-planet-nine commented on src/cpp/client/example/arduino/LEDTEST/Archive.zip
yep that's right. Removed, and added zip's to top-level gitignore.

2024-06-27 03:38 UTC, parkerstafford approved these changes

2024-06-27 06:07 UTC, merged