Rainbow test
planet-nine-app/sessionless pull request #61
Opened 2024-06-29 16:31 UTC by zach-planet-nine

This adds the rainbow test to the node cli (I'd like to update the other clis too, but it's lower priority than getting the rest of the example servers working). Right now it works with the javascript, typescript, rust, and c# implementations. The Java and Kotlin servers need to be updated to conform to the naming we settled on, and we need to build a python server.

2024-06-29 16:42 UTC, FssAy requested changes

2024-06-29 16:42 UTC, FssAy commented on src/rust/examples/slapper/src/requests/register.rs
Rust uses `snake_case` naming convention, but Sessionless uses `camelCase`. In order to comply with both it's possible to use serde attributes. These attributes can help rename the struct's fields when serialized.

The easiest way to fix that would be adding:
```rust
#[serde(rename_all="camelCase")]
```
on the line `32` just above:
```rust
struct RegisterPayload<'a> {
```

Then we can use `snake_case` variable names as all of them will be transformed to `camelCase` automatically.

2024-06-29 16:54 UTC, zach-planet-nine commented on src/rust/examples/slapper/src/requests/register.rs
Woof, this change must have been from long ago and I committed it and forgot about it. I can either revert to what's on main or make the change you suggest and clean up anything that might break.

2024-06-29 18:32 UTC, FssAy commented on src/rust/examples/slapper/src/requests/register.rs
I mean, if you revert that would create a bug as the fields won't be serialized in `camelCase`.

2024-06-29 20:51 UTC, zach-planet-nine commented on src/rust/examples/slapper/src/requests/register.rs
well that answers that. How's this update look?

2024-06-29 21:44 UTC, FssAy commented on src/rust/examples/slapper/src/requests/register.rs
Top 👌

2024-06-29 21:49 UTC, FssAy commented on src/java/spring/src/main/java/app/planentnine/springsessionless/adapter/web/UserController.java
Is it part of the Java implementation? I guess there is no longer need for the debug comments haha

2024-06-29 21:55 UTC, FssAy commented on src/csharp/examples/server/obj/project.nuget.cache
From what I've read just now, this file shouldn't be pushed to source control and added to `.gitignore`.

2024-06-29 21:57 UTC, FssAy commented on src/csharp/examples/server/users.json
I think we could also add this file to `.gitignore`, I believe it's runtime generated and will be overwritten every time.

2024-06-29 22:00 UTC, FssAy commented on src/java/spring/src/main/java/app/planentnine/springsessionless/adapter/web/.MessageController.java.swp
I think this also got here by an accident. I've found out it's a temporary file generated by Vim, but I am not sure.

2024-06-29 22:02 UTC, FssAy requested changes
I've just gazed through the code to find any parts that might got pushed by an accident.

2024-06-30 02:00 UTC, zach-planet-nine commented on src/java/spring/src/main/java/app/planentnine/springsessionless/adapter/web/.MessageController.java.swp
yeah... man I don't know what I was doing two weeks ago.

2024-06-30 02:09 UTC, zach-planet-nine commented on src/java/spring/src/main/java/app/planentnine/springsessionless/adapter/web/UserController.java
Ok I think this is ready for a second look. Sorry for the churn, and thanks for catching it.

2024-06-30 09:23 UTC, FssAy commented on src/csharp/examples/server/users.json
Great! I think that's the best solution here in that case.

2024-06-30 09:27 UTC, FssAy approved these changes
Looks good 👌

2024-06-30 16:08 UTC, merged