Added .d.ts for sessionless-node
planet-nine-app/sessionless pull request #77
Opened 2024-09-04 14:48 UTC by habomane

Not positive this is accurate. Please see file.

2024-09-13 01:35 UTC, zach-planet-nine commented on src/javascript/node/sessionless.d.ts
> +export declare const generateKeys: (getKey: () => {}, saveKey: () => {}) => Promise<{privateKey: string, publicKey: string}>;
this should be `getKeys`, and `saveKeys`

2024-09-13 01:35 UTC, zach-planet-nine commented on src/javascript/node/sessionless.d.ts
> +export declare const generateKeys: (getKey: () => {}, saveKey: () => {}) => Promise<{privateKey: string, publicKey: string}>;
So here, and for the return of generateKeys above, you should define a Keys type that has privateKey: string, and publicKey: string

2024-09-13 01:35 UTC, zach-planet-nine commented on src/javascript/node/sessionless.d.ts
> +export declare const verifySignature: (sig: {r: string, s:string}, message: string, pubKey: string) => boolean;
sig is just a string

2024-09-13 01:35 UTC, zach-planet-nine commented on src/javascript/node/sessionless.d.ts
> +export declare const associate: (primarySignature: {r: string, s:string}, primaryMessage: string, primaryPublicKey: string, secondarySignature: {r: string, s:string}, secondaryMessage: string, second
the signatures here are strings

2024-09-13 01:36 UTC, zach-planet-nine requested changes
changed to request changes

2025-02-12 04:01 UTC, ackle-dev commented
I can work on this, copying to my fork

2025-02-12 05:58 UTC, closed without merging